### ISSUE TITLE
Add focal channel for development

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-dev-packages-lfs#56]
As part of https://github.com/freedomofpress/securedrop/issues/4768 (Focal epic) we'll need to be able to upload and serve Focal packages via `apt-test.freedom.press`. This issue is intended to track the required changes to this repo's configuration.

**Comment by conorsch** [comment]
The only change required should be adding a new block to `repo/conf/distributions` with the focal block. Thereafter, packages can be added to `core/focal/` and it'll all Just Work™. At least, that's the plan! :smile:
